# Generated by Django 3.1.3 on 2020-11-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201125_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalrecord',
            name='latitude',
            field=models.FloatField(default=49.2827),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalrecord',
            name='longitude',
            field=models.FloatField(default=123.1207),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journalrecord',
            name='species',
            field=models.CharField(choices=[('Chum', 'Chum'), ('Coho', 'Coho'), ('Chinook', 'Chinook'), ('Pink', 'Pink'), ('Sockeye', 'Sockeye'), ('Trout', 'Trout')], max_length=50),
        ),
    ]
