# Generated by Django 3.1.3 on 2020-12-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201130_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalrecord',
            name='method',
            field=models.CharField(max_length=300),
        ),
    ]
