# Generated by Django 3.1.3 on 2020-12-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201202_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalrecord',
            name='size',
            field=models.FloatField(),
        ),
    ]
