# Generated by Django 3.1.3 on 2021-01-13 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201210_1133'),
        ('myapp', '0002_delete_test'),
    ]

    operations = [
    ]
