# Generated by Django 3.1.3 on 2021-01-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210113_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='colek', max_length=200),
            preserve_default=False,
        ),
    ]
